- name: Deploy my awesome site
  hosts: srv
  vars:
      var_domain_name: "awesome-site"
  tasks:
    - name: Upgrade packages
      apt:
        upgrade: full
        update_cache: true
    - name: Install apache2
      apt:
        name:
         [apache2, apache2-bin, apache2-data, apache2-utils]
        state: present
    - name: Create HTML dir
      file: 
        path: "var/www/{{ var_domain_name }}"
        owner: www-data
        group: www-data
        mode: '0755'
        state: directory
      register: var_html_dir
    - name: Unzip awesome-site
      src: "~/awesome-site.zip"
      dest: "{{ var_html_dir.path }}"
      extra_opts: [--strip-components=1]
    - name: Generate awesome-site config file
      template:
        src: "site.conf.js"
        dest: "/etc/apache2/sites-available/{{ var_domain_name }}.conf"
    - name: Enable awesome-site
      command: a2ensile "{{ var_domain_name }}"
      notify: Reload Apache2
  handlers:
    - name: Reload Apache2
      service:
        name: apache2
        state: reload

